"""empty message

Revision ID: 383ec1bbb04c
Revises: b2fd8acbcf7c
Create Date: 2021-08-06 14:33:24.034505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383ec1bbb04c'
down_revision = 'b2fd8acbcf7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Artist_genres',
    sa.Column('Artist_id', sa.Integer(), nullable=False),
    sa.Column('Genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['Genre_id'], ['Genre.id'], ),
    sa.PrimaryKeyConstraint('Artist_id', 'Genre_id')
    )
    op.drop_table('genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('genre', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='genre_pkey')
    )
    op.drop_table('Artist_genres')
    op.drop_table('Genre')
    # ### end Alembic commands ###
