"""empty message

Revision ID: 8f4e828162ed
Revises: 383ec1bbb04c
Create Date: 2021-08-06 15:00:12.501238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f4e828162ed'
down_revision = '383ec1bbb04c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('Artist', 'artist')
    op.rename_table('Genre', 'genre')
    op.rename_table('Venue', 'venue')
    op.rename_table('Artist_genres', 'artist_genres')
    
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('artist', 'Artist')
    op.rename_table('genre', 'Genre')
    op.rename_table('venue', 'Venue')
    op.rename_table('artist_genres', 'Artist_genres')
    # ### end Alembic commands ###
