"""empty message

Revision ID: 9d4452bf734c
Revises: 8f4e828162ed
Create Date: 2021-08-08 09:49:06.293960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d4452bf734c'
down_revision = '8f4e828162ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('artist', sa.Integer(), nullable=False),
    sa.Column('venue', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['venue'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.alter_column('artist_genres', 'Artist_id', new_column_name='artist_id')
    op.alter_column('artist_genres', 'Genre_id', new_column_name='genre_id')
   
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artist_genres', 'artist_id', new_column_name='Artist_id')
    op.alter_column('artist_genres', 'genre_id', new_column_name='Genre_id')

    op.drop_table('show')
    # ### end Alembic commands ###
