"""empty message

Revision ID: d185c53de535
Revises: 450fd63efe40
Create Date: 2021-08-10 16:46:47.285125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd185c53de535'
down_revision = '450fd63efe40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.add_column('show', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.drop_constraint('show_venue_fkey', 'show', type_='foreignkey')
    op.drop_constraint('show_artist_fkey', 'show', type_='foreignkey')
    op.create_foreign_key(None, 'show', 'venue', ['venue_id'], ['id'])
    op.create_foreign_key(None, 'show', 'artist', ['artist_id'], ['id'])
    op.drop_column('show', 'venue')
    op.drop_column('show', 'artist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('artist', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('show', sa.Column('venue', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.create_foreign_key('show_artist_fkey', 'show', 'artist', ['artist'], ['id'])
    op.create_foreign_key('show_venue_fkey', 'show', 'venue', ['venue'], ['id'])
    op.drop_column('show', 'venue_id')
    op.drop_column('show', 'artist_id')
    # ### end Alembic commands ###
