"""empty message

Revision ID: daec1576e416
Revises: 32344f3d6805
Create Date: 2021-08-12 12:10:30.092583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daec1576e416'
down_revision = '32344f3d6805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artist', 'website_link', new_column_name='website')
    op.alter_column('venue', 'website_link', new_column_name='website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artist', 'website', new_column_name='website_link')
    op.alter_column('venue', 'website', new_column_name='website_link')
    # ### end Alembic commands ###
